### ISSUE TITLE
Arrays && Slices && Pointers

### ISSUE THREAD

**Issue by 18plusui** [18plusui/dogetime#3]
这是我的第一篇技术blog，简单的说：“就是一次对知识的学习、梳理，并想通过自己的理解到的一些总结，并通过blog的形式传播并奢望得到反馈的过程”，总之我写了，如题:

> * 固长与底层引用的Arrays
> * 灵活动态的Slices
> * 普通而又有价值 Pointers
> * slice指针作为函数参数还会带来性能提升吗
> * 为何选择使用Slices

### [固长与底层引用的Arrays](https://golang.org/search?q=array)
其实Go语言中的数组的特性与其他语言本质是一样的。但这是为什么还要抽出来写，主要是前几天有一个网友提醒我：“我的算法在做数组拷贝”。这句话让我对Arrays有了深度的学习劲头，下面主要写一些我所理解到的Go语言中的Array。

数组的特性是固定长度/由零个或多个元素组成/具备索引值<从0开始到数组长度减1的位置>，同于一些语言中所用到的size，GO语言为数组长度测量提供了len。在后面写到Slices的时候，会多一个cap函数

简单的通过代码了解一下Array的基本特性
### Arrays 

```go
import (
	"fmt"
)

func main() {
	var a [3]int
	fmt.Println("init int arrays , defalut value 0", a)
	fmt.Println("the first element value", a[0])
	fmt.Println("the last element value", a[len(a)-1])

	for i, v := range a {
		fmt.Printf("index is : %d ; value is : %d\n", i, v)
	}

	// Print the elements only.
	for i, v := range a {
		a[i] = i
		fmt.Printf("origin value : %d ; after change value : %d\n",              v, a[i])
	}
	fmt.Println("after changed arrays :", a)

}

result：
	init int arrays , defalut value 0 [0 0 0]
	the first element value 0
	the last element value 0
	index is : 0 ; value is : 0
	index is : 1 ; value is : 0
	index is : 2 ; value is : 0
	origin value : 0 ; after change value : 0
	origin value : 0 ; after change value : 1
	origin value : 0 ; after change value : 2
	after changed arrays : [0 1 2]
```
------

### [灵活动态的Slices](https://golang.org/search?q=slice)
Slice（切片）代表可变长的序列，这个特性非常重要，正因为数组的长度是固定的，在很多场景下缺乏灵活性，而Slice估计是因此特性而生，Slice的语法特性先不写，它与数组大同小异，您也可以从下面的会用到的程序中对其语法特性做一下简单了解，而我重点写实现算法基础，如下：

Slice是一个轻量级的数据结构，它提供了访问数组子序列（或者全部）元素的功能，slice的底层是通过引用一个数组对象来构造的。这里涉及到slice的三个概念关于它的构成部分：指针、长度和容量。指针指向第一个slice元素对应的底层数组元素的地址，Slice的指针可以对应数据任意段的位置，这种灵活性为很多场景提供了极大数组操作上的便利。还有就是如上提到的cap函数，也即意味着slice除了有长度概念还有一个容量概念，但有个约束前提是：长度不能超过容量，容量一般是从slice的开始位置到底层数据的结尾位置。内置的len和cap函数分别返回slice的长度和容量

简单的代码了解一下Slice的基本特性
### Slices 

```go
package main

import (
	"fmt"
)

func main() {

	// with a size is Arrays:
	names1 := [3]string{"hello", "world", "18plusui"}
	fmt.Println("names1", names1)
	//or
	names2 := [3]string{}
	fmt.Println("names2 , you can see defalut value ", names2)
	// else is Slices:

	names3 := []string{"hello", "world", "18plusui"}
	fmt.Println("names3", names3)
	//or
	names4 := make([]string, 3, 6)
	fmt.Printf("length is : %d ; Cap is : %d\n", len(names4), cap(names4))
	//or
	var names5 []string

	fmt.Println("defalut slice is : ", names5)

}

result：
	names1 [hello world 18plusui]
	names2 , you can see defalut value  [  ]
	names3 [hello world 18plusui]
	length is : 3 ; Cap is : 6
	defalut slice is :  []

------
```
### [普通而又有价值 Pointers](https://golang.org/ref/spec#Pointer_types)
Pointer在go语言中也是一种类型，指针类型接收的是指针的对指向给定类型的变量。同时，未初始化的指针的值是nil。在Go语言中，用到了两个符号（*， &）来表示对指针的指向指针所指的值与引用，这里我可能表达得不够清晰，可以稍作思考来想我为什么这么说，没事我现在简单的解释一下：

 - 在GO语言中指针使用*字符后如果跟的是一个指针，则表示指针的存储值
 - 上诉的这种指针操作，只是运用于对指针指向value的操作，同时更为基础的是表示一个值的指针即用*表示就可以了
 - 要对指针赋值就用到了我刚才提到的两个符号中的另外一个 &
 
看一段程序：
### Pointer 

```go

package leetcode

func Zero(x int) {
	x = 0
}

func ZeroPtr(xPtr *int) {
	*xPtr = 0
	//从这个段程序即是对指针指向的值进行操作的表达，也即可我第一点提到的
}

//这里引用一段等会要用于性能测试的程序来展示，我提到的 & 符号的用法
func Benchmark_zero1(t *testing.B) {

	x := 5
	for i := 0; i < t.N; i++ {
	    // & 符号成功的将指向int类型x的指针赋值给了ZeroPtr这个函数
		ZeroPtr(&x)
	}
	fmt.Println(x)
}

------
```
最后，为什么标题要说Go的指针普通呢？就是因为Go语言的指针并不像C语言那样能做指针运算，为什么这么把指针设计成现在这样，我暂时没有能力去分析

### [slice指针作为函数参数还会带来性能提升吗](https://google.com)
讲完了三个很重要Go type，终于来到了这个话题,(ps:网友已经在我的基础上加上了对数组的压测，指针对数组的显示传入是有提升性能的效用的），我们接着做一下简单的实验，下面这段代码是对刚才pointer那段代码而写压测函数：
### Response time testing 

```go

package leetcode

import (
	"fmt"
	"testing"
)

func Benchmark_zero(t *testing.B) {

	x := 5
	for i := 0; i < t.N; i++ {
		Zero(x)
	}
	fmt.Println(x)
}

func Benchmark_zero1(t *testing.B) {

	x := 5
	for i := 0; i < t.N; i++ {
		ZeroPtr(&x)
	}
	fmt.Println(x)
}
reslut：
Benchmark_zero-4        5
5
5
5
5
5
2000000000               0.39 n
Benchmark_zero1-4       0
0
0
0
0
0
2000000000               0.57 n
ok      gosin/leetcode  4.198s
------
```
首先，这个测试有两个概念，第一通过指针引用来修改值，是会改变的，反之则不会，比如:第一段依旧是5，而第二却变为了0。最后，我经过了多次的压力测试，都发现指针引用没有带来性能的提升，反而对指针的操作时，反而更慢了，我担心这个结论与Gopl中给的建议是不同的，我担心是不是因为程序复杂度不够，不易看出差距，所以我加强算法复杂度来做测试，我引用了我今天写好的leetcode里面的2sum算法来再次做测试：

### Response time testing 

```go

package leetcode

import (
	"fmt"
)

func Sum2ptr(arr *[]int, target int) {

	arrLen := len(*arr)

	for i := 0; i < arrLen; i++ {

		for j := i + 1; j < arrLen; j++ {
			if target-(*arr)[i] == (*arr)[j] {
				fmt.Println((*arr)[i], (*arr)[j])
			}

		}
	}

}

func Sum2arr(arr []int, target int) {

	arrLen := len(arr)

	for i := 0; i < arrLen; i++ {

		for j := i + 1; j < arrLen; j++ {
			if target-arr[i] == arr[j] {
				fmt.Println(arr[i], arr[j])
			}

		}
	}

}

reslut：
Benchmark_Arr-4         N loop arr 1
N loop arr 100
N loop arr 10000
N loop arr 20000
   20000             66553 ns/op
Benchmark_Ptr-4         N loop ptr 1
N loop ptr 100
N loop ptr 10000
   10000            104906 ns/op
------
```
结果不难发现，当算法复杂度提高后，指针引用的response time 上表现得更为糟糕,所以我认为对指针接收的函数，其实并非为提升性能而造的，也许它使用指针会带来内存上的节省，但我感觉这更像我第一个用例里提到的,它可以通过指针来改变引用过来的值才是指针的关键。

### [为何选择使用Slices](http://github.com/18plusui/)
指针来传递数组参数虽然给程序带来了高效，但还是低于slice的直接操作，而且关键的关键就是我开篇一堆废话中提到的，数组依然是固定长度的类型，这让程序缺乏了灵活性，我有向很多高手讨论关于reflect && interface && 泛型的知识，这也是我下一个想写的topic，我发现一个问题，如果要为一些多样化的东西需要做各种判断考虑是不合理的，比如上面的Zero函数，如果被定长为[2]int类型数组的指针，而且也没有任何添加或删除数组元素的方法，这明显不合理。所以才会重点转用使用slice，并发挥其灵活性优势

考虑正确的使用Slice也顺里成章的成为了一个比较值得关注的话题，我从这半个月写leetcode的感受来说，我总结了如何正确的使用slice的2点细节：

 - Slice内存技巧
 比如，我昨天发的一条微博提及到的数字反转的程序中，经过找资料学习发现旋转slice、反转slice或在slice原有内存空间修改元素时，输入的slice和输出的slice共享一个底层数组，这避免分配另一个数组的内存，前提是如果你不在乎原始数据被覆盖为前提

 - 模仿Stack
 因为Go是没有封装好的stack，但Go slice追加数据的append函数，以及分配技巧让Go很容易生成具备stack特性的数据结构
引用几段代码：
```go
stack = append(stack, v)     // push v
top := stack[len(stack)-1]   // top of stack
stack = stack[:len(stack)-1] // pop
------
```

> 印证了许式伟在他视频里说到的一句话，Go语言会将一切可被替代的类型删除

最后，这篇文章我写得并不够精炼，我只是感觉这三个概念是需要有序的去理解，另外，当我去阅读别人代码的时候，我不断的问自己：“为什么别人这么写，它带来的好处是什么？”，所以才有了这篇文章，看完希望对您有用
 
                                P.S:虽然这是一篇不具备专业水准的文章，但还是转载希望注明出处

**Comment by s7v7nislands** [comment]
测试的方法有问题,书上说的引用快是指参数拷贝的时候.

```
import "testing"

func Zero(x [100000]int) {
	for i := range x {
		x[i] = 4
	}
}

func ZeroPtr(x []int) {
	for i := range x {
		x[i] = 4
	}
}

func Benchmark_zero(t *testing.B) {

	x := [100000]int{}
	for i := 0; i < t.N; i++ {
		Zero(x)
	}
}

func Benchmark_zero1(t *testing.B) {

	x := [100000]int{}
	for i := 0; i < t.N; i++ {
		ZeroPtr(x[:])
	}
}
```

```
➜  test go test -bench .
testing: warning: no tests to run
PASS
Benchmark_zero-4 	   10000	    149817 ns/op
Benchmark_zero1-4	   20000	     73943 ns/op
ok  	_/tmp/test	3.790s
```

**Comment by s7v7nislands** [comment]
```
func ZeroArr(x *[100000]int) {
	for i := range x {
		x[i] = 4
	}
}
func Benchmark_zero2(t *testing.B) {

	x := [100000]int{}
	for i := 0; i < t.N; i++ {
		ZeroArr(&x)
	}
}
```

**Comment by s7v7nislands** [comment]
这样比较清晰了

**Comment by 18plusui** [comment]
你这段跑个结果出来

**Comment by s7v7nislands** [comment]
```
➜  test go test -bench .
testing: warning: no tests to run
PASS
Benchmark_zero-4 	   10000	    155090 ns/op
Benchmark_zero1-4	   20000	     77148 ns/op
Benchmark_zero2-4	   20000	     87295 ns/op
ok  	_/tmp/test	6.525s
➜  test 
```

**Comment by 18plusui** [comment]
嗯，没错，其实我应该纠正一下我的说法，因为我的测试模型本质上就是拿slice去做的测试，所以测出来的结果和你的结论是一致的

**Comment by s7v7nislands** [comment]
文章字太多没仔细看,反正我认为在golang里面slice其实就是对array指针的模拟,类似语法糖.

**Comment by wizardforcel** [comment]
slice是引用类型（貌似叫引用语义？），传slice的时候应该不涉及到复制吧。

**Comment by 18plusui** [comment]
嗯，是有人这么提醒我
