### ISSUE TITLE
评：yin神的《对 Go 语言的综合评价》

### ISSUE THREAD

**Issue by 18plusui** [18plusui/dogetime#5]
# 评：yin神的《对 Go 语言的综合评价》

------

我是一个愚蠢至极的人，我居然要向yin神写的东西提出异议

前几天alphago火了，朋友圈里怒刷了yin神关于alphago的文章，外加上一个朋友之前推荐过他，所以我顺势的通过简书往下读，今天读到**给java说句公道话** 这篇文章时，挖出了对他go语言的综合评价这篇文章：

我花了一个上午的时间，现在已经11：12了，我觉得我应该对这篇文章的阅读写一些自己读后感：

yin神认为：
> 但是请注意，这里的所谓“优点”都是相对于 C 之类的语言而言的。如果比起另外的一些语言，Go 的这种优点也许就很微不足道，甚至是历史的倒退了。

一开篇就很刺激，接着看：yin神的文章非常有循序渐进的把控，他第一个说的是：语法，并列举了如下问题：

 1. type 后置，扰乱视线
 2. 语法一致性上存疑，比如：[]\*Struct这种没什么，那这种：[]\*pkg.Struct呢？
 3. 过度地“语法重载”，比如switch存在两种可能性，会增加了人脑的开销
 
这里先提一下，整篇文章看得出yin神对Racket是有爱的，在讲到语法一致性问题时，yin神表示：Go不如Java或Typed Racket的类型写法来得清晰和简单。

其实这写到后面看起来也没那么困难费劲吧！略过到2，*不就代表指针引用嘛，[]不就代表存放了指针的slice，没有很强烈的视觉冲击感，我倒是发现另外一种弊病，比如：
```go
var array [3]string
//如果遇到显式指针传递参数的函数
func (inputArr *[3]string){
   //就会出现代码极其丑陋的地方
   (*inputArr)[]
}
```
这里不得不说的是，如我上一篇文章里写的，其实对数组的使用完全可以规避的，那并不是一篇入门文章，那里有深入的思考与论证，那篇显式指针的函数可以带来性能的提升，但是不足于直接使用slice来得快的呀，所以最丑陋的地方几乎以后都不会出现在大家的视野里了，如果出现了一定是哪里理解错了

yin神接着道来：
关于语法重载的问题：是因为它夹含了C中的switch功能，也包含了scheme cond，我特地查了关于cond的使用：[Racket 中的cond][1]，其实不难发现其包含了一些判断性质

在这里我不得不要插一句话：像这使用性上出现判别性的问题，我之前遇到过，也贴出来了，比如：reverse number 交换的那一句：
```go
func reverse(s []int) {
    for i, j := 0, len(s)-1; i < j; i, j = i+1, j-1 {
        s[i], s[j] = s[j], s[i]
    }
}
```
这种语法隐藏了一些东西temp交换上的动作，有大神给我解释说是：“语法糖”，可能这种理解性的隐藏确实不好，但不至于说烂，通俗的再打个比方：键盘上的“"”，他在中文的时候是两种<左/右引号>，在英文的时候是一种，不能说这键盘设计得太垃圾，过度的重载，因为根本不知道可能发生哪一种引号，但随着熟悉之后，其实这事够不成“增加了人脑的开销扰”的说法

yin神接着说工具链：

> Go虽然有gofmt & godef，但 Eclipse, IntelliJ 和 Visual Studio 这样的 IDE，差距还是相当大的。比起 IDE，Go 的工具链缺乏各种最基本的功能，比如列出引用了某个变量的所有位置，重命名等 refactor 功能，好用的 debugger （GDB 不算好用）

诶，这一点嘛，IDE不好使,Go只能说：“那怪我咯”，我看过一个视频关于：Andrew and Brad part write code，看完兴奋且立即找起了安装vim-go的资源，那效率与跳跃性比100个人之前告诉我vim学学很有必要还来劲，至于debugger嘛，其实不管是我还是我看到的很多go语言开发者，都已经逐渐忘记debug这事了，他们几乎用fmt完成了大部分程序的调试，以及顺便提一下go test机制是非常便捷的，还可以性能测试哦！！

关于godep yin神实在按捺不住自己的情绪了，来了一句:

> 我发现很多人看到这些工具之后总是很狂热的认为它们就能让 Go 语言一统天下，其实还差得非常之远。而且如此年轻的语言就已经出现这么多的问题，我觉得所有这些麻烦事累积下来，多年以后恐怕够呛。

哎，没想到直接 import 某个 GitHub repository 里的 Go 代码，会让yin神如此堪忧，我倒觉得还好，如果godep出问题了，它肯定会变好，如果事实证明这不是一种好的机制，我倒没那么悲观甚至表现出绝望，我反倒相信会有更好的机制去替代它，再说了这不是语言的核心根本，年轻这个词我把它理解成“轻”，其实不是任何轻的东西都会随着时间变成“重”，C语言相对来说还是很轻呀，再说轻也不代表轻就不会出现问题，现实生活中，一个小孩子虽然是单纯可人，但不代表这小孩是没有毛病的，关键还是在于如何引导发展

yin神接着说：

> 没有“generics”，Generics 其实就是 Haskell 等函数式语言里面所谓的 parametric polymorphism，是一种非常有用的东西，不过被 Java 抄去之后有时候没有做得全对

对，没有generics很多工作多年的人都提到这点极其重要，这是编程语言对类型编译上做的文章，我在我的上篇文章里提到过我要写这个话题的，没想到这里遇上了，我在这个问题上第一个想到的就是go的empty interface 没想到yin神也提到了这事，让我感到很嗨皮，我思考的东西方向已经似乎擦到边了，虽然yin神在文章里聊到了空接口，但他是不那么care的，就我对空接口的使用而言，我揣摩到一些不错的地方，先用一段JAVA程序来认识generics：
```java
Elimination of casts.
The following code snippet without generics requires casting:
List list = new ArrayList();
list.add("hello");
String s = (String) list.get(0);

re-written to use generics, the code does not require casting:
List<String> list = new ArrayList<String>();
list.add("hello");
String s = list.get(0);   // no cast
```
非常大的可能性是隐式的类型转换，或许有更高明的办法，但有无泛型的关键在于yin神所说的这句：Go没有 generics，所以你不得不重复写很多函数

我倒不这么认为,如果是涉及了隐式转换问题，空接口在go其实还挺好，写mongodb的一个执行命令时，可能会遇到如下代码，大家也知道mongodb的语法输入的并不单一，比如：JSON/string etc
```go
func MongoDB(operate string, option map[string]interface{}) error {
	o := getOperator(operate)
	if o == nil {
		return errors.New("haha，yinshen，I'm error")
	}

	v := reflect.ValueOf(o).Elem()
	for key, val := range option {

		value := v.FieldByName(key)

		if value == (reflect.Value{}) || !value.CanSet() {
			continue
		}
		value.Set(reflect.ValueOf(val))
	}

	return o
}
```
其实，我相信你已经明白了，这种写法我在非常多的开源项目上都看过，并没有想象中的那么愚蠢：要重复写func，这也是我与某大神聊过关于泛型与go语言中空接口的一个话题时，我举的例子，没想到居然在这用上了

yin神接着说：
你居然跟我提接口，等会我再数落你，我先来说说go的多值返回就是一个错误：
```go
ret, err := foo(x, y, z)
if err != nil {
    return err
}

ret, _ := foo(x, y, z)
```
yin神认为，如果多值返回用于err不是就设计的根本，如果不想检测err则用第二段程序，上面这种做法，引用yin神的话就是：
> 不得不说，这种“歪打正着”的做法虽然貌似可行，从类型系统角度看，却是非常不严谨的。

但yin神后面的一些假设真的非常深刻，他提到：

> 比如，如果 foo 可能返回两种错误 Error1 和 Error2，你没法保证调用者完全排除了这两种错误的可能性之后才使用数据。所以这种错误检查机制其实还不如 Java 的 exception 来的严谨

是的，我非常赞同这一点，如果从exception上去区分错误才是最合理的，我平时写代码的时候，我看一眼err，我大概知道错了什么，在代码的第几行，除此之外一无所获，而如果做了区分可能会更深入直观一点。另外，yin神在这个地方又傲娇了，他拿出了开篇我说的对Racket有爱，他讲述到：

> 对 union type 有兴趣的人可以看看 Typed Racket，它拥有我迄今为止见过最强大的类型系统（超越了 Haskell）

大概的意思就是说，go的多值返回没有什么可说的了，你们还是去学学什么是union type吧，我是很初级的玩家，我甚至愚蠢到用多值来给程序在开发期间来做类似debug的返回，还有对array/slice 的for range，逻辑上的ok button判断而且乐在其中，还对range出来索引值的应用得理所当然，但我估计这些东西都是愚蠢的程序员用的，不入yin神法眼的，那就继续吧！

如果yin神不巧也看了这篇文章，他心里肯定会欣慰的说：“还好，我怒斥了go的interface type，yin神说：

> 实现一个 Go 的接口不需要显式的声明（implements），所以你有可能“碰巧”实现了某个接口。这种不确定性对于理解程序来说是有反作用的。有时候你修改了一个函数之后就发现编译不通过，抱怨某个位置传递的不是某个需要的接口，然而出错信息却不能告诉你准确的原因。要经过一番摸索你才发现你的 struct 为什么不再实现之前定义的一个接口。

这一点我也极其赞同，因为我在学习的时候思考过这个问题，甚至，我在完成skyline problem的时候，还重新实现了sort对point的排序，真的好巧
```go
type point struct {
	x int
	y int
}

type arrPoint []point

func (s arrPoint) Len() int      { return len(s) }
func (s arrPoint) Swap(i, j int) { s[i], s[j] = s[j], s[i] }

type ByX struct{ arrPoint }

func (s ByX) Less(i, j int) bool {

	if s.arrPoint[i].x == s.arrPoint[j].x && s.arrPoint[i].y <= s.arrPoint[j].y {
		return true
	}
	return s.arrPoint[i].x < s.arrPoint[j].x
}
```
咦，看这个愚蠢的孩子的代码好像也还好！！
yin神继续说到：

> 由于 Go 没有 generics，你无法像函数式语言一样写这三个函数，接受比较的“元素”作为参数，而必须使用它们的“下标”。由于这些方法只接受下标作为参数，所以 Sort 只能对数组进行排序。另外由于 Go 的设计比较“底层”，所以你需要另外两个参数: len 和 swap。

好吧，又把泛型扯起来了，这里我必须说说我的感悟了：“go语言的接口是站在比较底层的角度上去看的，比如：io.Writer类型是用的最广泛的接口之一，因为它提供了所有的类型写入bytes的抽象，包括文件类型，内存缓冲区，网络链接，HTTP客户端，压缩工具，哈希等等。io包中定义了很多其它有用的接口类型。Reader可以代表任意可以读取bytes的类型，Closer可以是任意可以关闭的值，例如一个文件或是网络链接。（你可能注意到了很多Go语言中单方法接口的命名习惯）,虽然，我在学习go的时候，也发现go的接口实现方式真的略失优美，甚至问过几个go方面的践行者，怎么会这样，感觉好突兀，我从表象以及感官上都这么认为的，但事实上，Linus的书里曾提过一句话大概是：我非常喜欢unix至今仍是，因为它非常简洁，他对整个操作系统都抽象为了IO/OPEN/CLOSE/Fork……，所以，关于接口的定义其实是有两面性的，就看一个人的觉悟到底高不高，这会决定着有没有可能滥用接口，gopl里面对接口这章对这种问题其实也有一定的阐述，推荐阅读

yin神继续说到：

> goroutine 其实并不是像很多人想象的那样全新的，革命性的，独一无二的东西。只要有足够的动力，其它语言都能添加这个东西。

其实，goroutine很厉害吗？我只知道它很简单。对我而言，我也没办法从底层评估，但yin神已经帮我做了结论了，他说虽然CPS没什么，他的导师都是这方面的专家，但他最后还强调了一句：“语言在CPS方面实现效率是有区别的”，我相信他是说其实go做得还不错，不知为何还不情不愿的补了一句：“只要有足够动力去就能增加这个东西”这是哪出呀，我一直都记着一个论调：“面对高并发时，分岔路口在于你选择的是异步调用还是协程的方式来完成吗”？，怎么搞得现在全部语言都可以随时加入这协程阵营的架势，我应该把这一点记起来，以后想得明白的时候再继续想，既然yin神没提起goroutine 会聊到的select，我也不想提，因为这样会把话题引开

我觉得写到这我可以收篇了，因为下面接着讨论的是defer（也就是finally），对这种说：“写在一些语法的前面会造成滥用”的说法，我再次感觉到有一点悲观，反正在我受到影响的价值观里：“写程序就是一场打草稿的过程”，所以，会不会滥用还是得看自身，另外go语言的空接口有一定的动态性以及还能帮助到go语言成为具有面向对象思考方式，对我来说是对思维的一种发散，也是打“草稿”期间给思考足够多的宽限，我甚至也相信最后go会有泛型，这没什么，因为它目前的缺陷还不足于影响我要完成我想要的，至于template，切确的说是html template，我也觉得也无所谓，我上午才计划学学写写js，我看看当前端这伟大的行业，除html有了解的我，深入到我的编程思想时，我会不会觉得go的template嵌入的语法是否是反人类的设计

  [1]: https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket/private/letstx-scheme..rkt%29._cond%29%29%20%E2%80%9Ccond%E2%80%9D

**Comment by erylee** [comment]
yin神对go是客气的，go是失败的plan9项目的烂尾。

**Comment by wizardforcel** [comment]
golang没有多值返回，那叫“返回元组并赋值解构”。

**Comment by wizardforcel** [comment]
golang的类型实在是保留了一些c的糟粕（c++也一样）。比起c来倒是有点进步，不用倒腾数组/字符串/哈希表了，但还不能跟java比。java/c#（以及一些脚本语言）的类型遵循一种“二分法”，要么是值类型，要么是引用类型，golang的类型除了少数几个官方钦定的引用语义，都可以放在栈上或堆上，用的人还得去区分哪些是引用语义。
